//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntitiesDbContext : DbContext
    {
        public FitnessEntitiesDbContext()
            : base("name=FitnessEntitiesDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassMembershipType> ClassMembershipTypes { get; set; }
        public virtual DbSet<ClassTime> ClassTimes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<NotavailableDatetime> NotavailableDatetimes { get; set; }
        public virtual DbSet<ScheduleClass> ScheduleClasses { get; set; }
        public virtual DbSet<ScheduleTrainer> ScheduleTrainers { get; set; }
        public virtual DbSet<Trainerrate> Trainerrates { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
    }
}
