//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleClass
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> classid { get; set; }
        public Nullable<int> Membershiptype { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ClassMembershipType ClassMembershipType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
