//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTrainer
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TrainerId { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public Nullable<bool> AppointmentStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
